import { clsx, type ClassValue } from "clsx"
import { twMerge } from "tailwind-merge"
import i18n from "i18next";
import { initReactI18next } from "react-i18next";
import LanguageDetector from "i18next-browser-languagedetector";

const resources = {
  en: {
    translation: {
      "welcome": "Welcome to Farmer AI Buddy!",
      "ai_farm_assistant": "AI Farm Assistant",
      "get_instant_answers": "Get instant answers to your farming questions",
      "hero.alt_modern_farming": "Modern farming with AI technology",
      "hero.title1": "Your AI-Powered",
      "hero.title2": "Farming Assistant",
      "hero.subtitle": "Get personalized agricultural advice, plant identification, weather insights, and market data - all in your local language, accessible anywhere.",
      "hero.start_chat": "Start Chat Assistant",
      "hero.identify_plants": "Identify Plants",
      "hero.ai_chat_title": "AI Chat Assistant",
      "hero.ai_chat_desc": "Get instant answers about crops, diseases, and farming practices in your language",
      "hero.weather_title": "Weather Intelligence",
      "hero.weather_desc": "Real-time weather data and climate-smart recommendations for your location",
      "hero.market_title": "Market Insights",
      "hero.market_desc": "Access current market prices and trends to maximize your profits",
      "nav.home": "Home",
      "nav.ai_assistant": "AI Assistant",
      "nav.weather": "Weather",
      "nav.market": "Market",
      "nav.plant_id": "Plant ID",
      "nav.brand": "FarmAI",
      "nav.brand_full": "FarmAI Assistant",
      "nav.brand_subtitle": "",
      "chatbot.ready_to_help": "Always ready to help",
      "chatbot.input_placeholder": "Ask about crops, diseases, weather, or market prices...",
      "chatbot.start_listening": "Start voice input",
      "chatbot.stop_listening": "Stop voice input",
      "chatbot.speech_mode": "Speech Mode",
      "chatbot.play_response": "Play response",
      "weather.loading": "Loading weather data...",
      "weather.error": "Failed to fetch weather data.",
      "weather.listen": "Listen",
      "weather.current_weather_in": "Current weather in {{city}}",
      "weather.temp": "Temperature",
      "weather.humidity": "Humidity",
      "weather.rainfall": "Rainfall",
      "weather.wind": "Wind Speed",
      "weather.condition": "Condition",
      "weather.visibility": "Visibility",
      "weather.forecast": "Forecast",
      "weather.drought_alert": "Drought risk: Consider irrigation",
      "weather.heavy_rain_alert": "Heavy rain alert: Protect crops",
      "weather.irrigation_suggest": "Irrigation needed due to high temperature",
      "weather.growing_season": "Good growing season conditions",
      "weather.disease_risk": "High humidity: Disease risk",
      "nav.soil_crop_advice": "Soil & Crop Advice",
      "nav.pest_disease": "Pest & Disease Detection",
      // Add more keys as needed
    },
  },
  ta: {
    translation: {
      "welcome": "விவசாயி ஏஐ நண்பருக்கு வரவேற்கிறோம்!",
      "ai_farm_assistant": "ஏஐ விவசாயி உதவியாளர்",
      "get_instant_answers": "உங்கள் விவசாய கேள்விகளுக்கு உடனடி பதில்கள் பெறுங்கள்",
      "hero.alt_modern_farming": "ஏஐ தொழில்நுட்பத்துடன் நவீன விவசாயம்",
      "hero.title1": "உங்கள் ஏஐ இயக்கப்படும்",
      "hero.title2": "விவசாய உதவியாளர்",
      "hero.subtitle": "தனிப்பயன் விவசாய ஆலோசனை, தாவர அடையாளம், வானிலை தகவல்கள் மற்றும் சந்தை தரவுகள் - உங்கள் உள்ளூர் மொழியில், எங்கும் அணுகக்கூடியது.",
      "hero.start_chat": "உதவியாளருடன் உரையாட தொடங்கு",
      "hero.identify_plants": "தாவரங்களை அடையாளம் காண்க",
      "hero.ai_chat_title": "ஏஐ உரையாடல் உதவியாளர்",
      "hero.ai_chat_desc": "உங்கள் மொழியில் பயிர்கள், நோய்கள் மற்றும் விவசாய நடைமுறைகள் குறித்து உடனடி பதில்கள் பெறுங்கள்",
      "hero.weather_title": "வானிலை நுண்ணறிவு",
      "hero.weather_desc": "உங்கள் இடத்திற்கு நேரடி வானிலை தரவு மற்றும் காலநிலை பரிந்துரைகள்",
      "hero.market_title": "சந்தை தகவல்கள்",
      "hero.market_desc": "உங்கள் லாபத்தை அதிகரிக்க தற்போதைய சந்தை விலைகள் மற்றும் போக்குகளை அறியுங்கள்",
      "nav.home": "முகப்பு",
      "nav.ai_assistant": "ஏஐ உதவியாளர்",
      "nav.weather": "வானிலை",
      "nav.market": "சந்தை",
      "nav.plant_id": "தாவர அடையாளம்",
      "nav.brand": "FarmAI",
      "nav.brand_full": "FarmAI உதவியாளர்",
      "nav.brand_subtitle": "",
      "chatbot.ready_to_help": "எப்போதும் உதவ தயாராக உள்ளது",
      "chatbot.input_placeholder": "பயிர்கள், நோய்கள், வானிலை, சந்தை விலைகள் குறித்து கேளுங்கள்...",
      "chatbot.start_listening": "குரல் உள்ளீட்டை தொடங்கு",
      "chatbot.stop_listening": "குரல் உள்ளீட்டை நிறுத்து",
      "chatbot.speech_mode": "குரல் பயன்முறை",
      "chatbot.play_response": "பதில் வாசிக்க",
      "weather.loading": "வானிலை தரவு ஏற்றப்படுகிறது...",
      "weather.error": "வானிலை தரவை பெற முடியவில்லை.",
      "weather.listen": "வானிலை கேளுங்கள்",
      "weather.current_weather_in": "{{city}} இல் தற்போதைய வானிலை",
      "weather.temp": "வெப்பநிலை",
      "weather.humidity": "ஈரப்பதம்",
      "weather.rainfall": "மழை அளவு",
      "weather.wind": "காற்று வேகம்",
      "weather.condition": "நிலைமை",
      "weather.visibility": "பார்வை தூரம்",
      "weather.forecast": "முன்னறிவு",
      "weather.drought_alert": "வறட்சி அபாயம்: பாசனத்தை பரிசீலிக்கவும்",
      "weather.heavy_rain_alert": "கடுமையான மழை எச்சரிக்கை: பயிர்களை பாதுகாக்கவும்",
      "weather.irrigation_suggest": "உயர் வெப்பநிலை: பாசனம் தேவை",
      "weather.growing_season": "நல்ல வளர்ச்சி பருவ நிலை",
      "weather.disease_risk": "உயர் ஈரப்பதம்: நோய் அபாயம்",
      "nav.soil_crop_advice": "மண் மற்றும் பயிர் ஆலோசனை",
      "nav.pest_disease": "பூச்சி மற்றும் நோய் கண்டறிதல்",
      // Add more keys as needed
    },
  },
  hi: {
    translation: {
      "welcome": "किसान एआई बडी में आपका स्वागत है!",
      "ai_farm_assistant": "एआई कृषि सहायक",
      "get_instant_answers": "अपने कृषि प्रश्नों के त्वरित उत्तर प्राप्त करें",
      "hero.alt_modern_farming": "एआई तकनीक के साथ आधुनिक कृषि",
      "hero.title1": "आपका एआई-संचालित",
      "hero.title2": "कृषि सहायक",
      "hero.subtitle": "व्यक्तिगत कृषि सलाह, पौधों की पहचान, मौसम की जानकारी और बाजार डेटा - आपकी स्थानीय भाषा में, कहीं भी उपलब्ध।",
      "hero.start_chat": "चैट सहायक शुरू करें",
      "hero.identify_plants": "पौधों की पहचान करें",
      "hero.ai_chat_title": "एआई चैट सहायक",
      "hero.ai_chat_desc": "अपनी भाषा में फसलों, बीमारियों और कृषि प्रथाओं के बारे में तुरंत उत्तर प्राप्त करें",
      "hero.weather_title": "मौसम बुद्धिमत्ता",
      "hero.weather_desc": "आपके स्थान के लिए रीयल-टाइम मौसम डेटा और जलवायु-स्मार्ट सिफारिशें",
      "hero.market_title": "बाजार अंतर्दृष्टि",
      "hero.market_desc": "अपने लाभ को अधिकतम करने के लिए वर्तमान बाजार मूल्य और रुझान प्राप्त करें",
      "nav.home": "मुखपृष्ठ",
      "nav.ai_assistant": "एआई सहायक",
      "nav.weather": "मौसम",
      "nav.market": "बाजार",
      "nav.plant_id": "पौधों की पहचान",
      "nav.brand": "FarmAI",
      "nav.brand_full": "FarmAI सहायक",
      "nav.brand_subtitle": "",
      "chatbot.ready_to_help": "हमेशा मदद के लिए तैयार",
      "chatbot.input_placeholder": "फसलों, बीमारियों, मौसम या बाजार मूल्यों के बारे में पूछें...",
      "chatbot.start_listening": "वॉयस इनपुट शुरू करें",
      "chatbot.stop_listening": "वॉयस इनपुट रोकें",
      "chatbot.speech_mode": "वाणी मोड",
      "chatbot.play_response": "उत्तर सुनें",
      "weather.loading": "मौसम डेटा लोड हो रहा है...",
      "weather.error": "मौसम डेटा प्राप्त करने में विफल.",
      "weather.listen": "मौसम सुनें",
      "weather.current_weather_in": "{{city}} में वर्तमान मौसम",
      "weather.temp": "तापमान",
      "weather.humidity": "नमी",
      "weather.rainfall": "वर्षा",
      "weather.wind": "हवा की गति",
      "weather.condition": "स्थिति",
      "weather.visibility": "दृश्यता",
      "weather.forecast": "पूर्वानुमान",
      "weather.drought_alert": "सूखा जोखिम: सिंचाई पर विचार करें",
      "weather.heavy_rain_alert": "भारी वर्षा की चेतावनी: फसलों की सुरक्षा करें",
      "weather.irrigation_suggest": "उच्च तापमान: सिंचाई आवश्यक",
      "weather.growing_season": "अच्छे बढ़ने के मौसम की स्थिति",
      "weather.disease_risk": "अधिक नमी: रोग का जोखिम",
      "nav.soil_crop_advice": "मिट्टी और फसल सलाह",
      "nav.pest_disease": "कीट और रोग पहचान",
      // Add more keys as needed
    },
  },
  te: {
    translation: {
      "welcome": "వివచాయి ఏఐ నాన్నికి స్వాగతం!",
      "ai_farm_assistant": "ఏఐ వివచాయి సహాయకుడు",
      "get_instant_answers": "మీ వివచాయ ప్రశ్నలకు తదుపరి ఉత్తరాలు పొందండి",
      "hero.alt_modern_farming": "ఏఐ తకనికీయాన్నించి న్యూన వివచాయి",
      "hero.title1": "మీ ఏఐ ఆధారిత",
      "hero.title2": "వివచాయి సహాయకుడు",
      "hero.subtitle": "వ్యక్తిగత వివచాయి సమాధానం, పੁట్టిన గుర్తింపు, వాతావరణ మానిక്కുకോవడం మరియు మార్కెట్ డేటా - మీ స్థానిక భాషలో, ఎక్కడ అంతర్గత్గారు.",
      "hero.start_chat": "సహాయకుడుతో చాట్ ప్రారంభించండి",
      "hero.identify_plants": "పుట్టిన గుర్తింపు చేయండి",
      "hero.ai_chat_title": "ఏఐ చాట్ సహాయకుడు",
      "hero.ai_chat_desc": "మీ భాషలో విళకలు, వ్యాధులు మరియు వివచాయి ప్రాస్త్రాల గురించి తదుపరి ఉత్తరాలు పొందండి",
      "hero.weather_title": "వాతావరణ మానిక്కുకോవడం",
      "hero.weather_desc": "మీ స్థానంలో వాస్తవ సమయం వాతావరణ డేటా మరియు జలవాయુ స్మార్ట్ సిఫారిస్లు",
      "hero.market_title": "మార్కెట్ అంతర్దృష్టి",
      "hero.market_desc": "మీ లాభాన్ని అధికించడానికి వర్తమాన మార్కెట్ ధరలు మరియు పోక్కులను అడిగండి",
      "nav.home": "హోమ్",
      "nav.ai_assistant": "ఏఐ సహాయకుడు",
      "nav.weather": "వాతావరణం",
      "nav.market": "మార్కెట్",
      "nav.plant_id": "సస్య గుర్తింపు",
      "nav.brand": "FarmAI",
      "nav.brand_full": "FarmAI సహాయకుడు",
      "nav.brand_subtitle": "",
      "chatbot.ready_to_help": "సహాయం చేయడానికి సిద్ధంగా ఉంది",
      "chatbot.input_placeholder": "పంటలు, వ్యాధులు, వాతావరణం, మార్కెట్ ధరల గురించి అడగండి...",
      "chatbot.speech_mode": "వాయిస్ మోడ్",
      "chatbot.play_response": "స్పీక్ చేయండి",
      "weather.loading": "వాతావరణ డేటా లోడ్ అవుతోంది...",
      "weather.error": "వాతావరణ డేటా పొందడంలో విఫలమైంది.",
      "weather.listen": "వినండి",
      "weather.current_weather_in": "{{city}} లో ప్రస్తుత వాతావరణం",
      "weather.temp": "ఉష్ణోగ్రత",
      "weather.humidity": "ఆర్ద్రత",
      "weather.rainfall": "వర్షపాతం",
      "weather.wind": "గాలి వేగం",
      "weather.condition": "స్థితి",
      "weather.visibility": "దృశ్యత",
      "weather.forecast": "అనుమానం",
      "weather.drought_alert": "ఎండ ప్రమాదం: నీటిపారుదల పరిగణించండి",
      "weather.heavy_rain_alert": "భారీ వర్షం హెచ్చరిక: పంటలను రక్షించండి",
      "weather.irrigation_suggest": "ఎక్కువ ఉష్ణోగ్రత: నీటిపారుదల అగత్యం",
      "weather.growing_season": "మంచి పెరుగుదల కాలం పరిస్థితులు",
      "weather.disease_risk": "ఎక్కువ ఆర్ద్రత: వ్యాధి ప్రమాదం",
      "nav.soil_crop_advice": "నేల మరియు పంట సలహా",
      "nav.pest_disease": "పురుగు మరియు వ్యాధి గుర్తింపు",
    },
  },
  ml: {
    translation: {
      "welcome": "ഹോം",
      "ai_farm_assistant": "എഐ സഹായി",
      "get_instant_answers": "നിങ്ങളുടെ കൃഷി പ്രശ്നങ്ങൾക്കുള്ളുള്ള ത്വരിക്ക് ഉത്തരങ്ങൾ ലഭ്യമാക്കുക",
      "hero.alt_modern_farming": "ഏഐ തകനിക്കീയാന്നിംചി ന്യൂന കൃഷി",
      "hero.title1": "നിങ്ങളുടെ ഏഐ ആധാരിത",
      "hero.title2": "കൃഷി സഹായി",
      "hero.subtitle": "വ്യക്തിഗത കൃഷി സമാധാനം, പുട്ടിന്റെ ഗുര്തിംപു, വാതാവരണ മാനിക്കുകോവഡം മരിയും മാര്ക്കെട്ട് ഡാറ്റ",
      "hero.start_chat": "സഹായിക്കുഡ്തോ ചാട് പ്രാരംഭിക്കുക",
      "hero.identify_plants": "പുട്ടിന്റെ ഗുര്തിംപു ചേയുക",
      "hero.ai_chat_title": "എഐ ചാട് സഹായി",
      "hero.ai_chat_desc": "നിങ്ങളുടെ ഭാഷയിൽ വിളകൾ, രോഗങ്ങൾ മരിയും കൃഷി പ്രാസ്ത്രാല്ലെക്കുറിച്ചുള്ള ത്വരിക്ക് ഉത്തരങ്ങൾ ലഭ്യമാക്കുക",
      "hero.weather_title": "വാതാവരണ മാനിക്കുകോവഡം",
      "hero.weather_desc": "നിങ്ങളുടെ സ്ഥാനംലോ വാസ്തവ സമയം വാതാവരണ ഡാറ്റ മരിയും ജലവായു സ്മാര്ട് സിഫാരിസ്ലുകൾ",
      "hero.market_title": "മാര്ക്കെട്ട് അംതര്ദൃഷ്ടി",
      "hero.market_desc": "നിങ്ങളുടെ ലാഭാന്നിന് അധികിക്കുക വര്ത്തക മാര്ക്കെട്ട് ധരങ്ങൾ മരിയും പോക്കുകൾ അറിയുക",
      "nav.home": "ഹോം",
      "nav.ai_assistant": "എഐ സഹായി",
      "nav.weather": "കാലാവസ്ഥ",
      "nav.market": "മാർക്കറ്റ്",
      "nav.plant_id": "സസ്യ തിരിച്ചറിയൽ",
      "nav.brand": "FarmAI",
      "nav.brand_full": "FarmAI സഹായി",
      "nav.brand_subtitle": "",
      "chatbot.ready_to_help": "സഹായിക്കാൻ എപ്പോഴും തയ്യാറാണ്",
      "chatbot.input_placeholder": "വിളകൾ, രോഗങ്ങൾ, കാലാവസ്ഥ, മാർക്കറ്റ് വിലകൾ എന്നിവയെക്കുറിച്ച് ചോദിക്കുക...",
      "chatbot.speech_mode": "വോയ്സ് മോഡ്",
      "chatbot.play_response": "ഉത്തരം വായിക്കുക",
      "weather.loading": "കാലാവസ്ഥ ഡാറ്റ ലോഡ് ചെയ്യുന്നു...",
      "weather.error": "കാലാവസ്ഥ ഡാറ്റ ലഭ്യമാക്കാൻ പരാജയപ്പെട്ടു.",
      "weather.listen": "ശ്രദ്ധിക്കുക",
      "weather.current_weather_in": "{{city}}-ലുള്ള നിലവിലെ കാലാവസ്ഥ",
      "weather.temp": "താപനില",
      "weather.humidity": "ആർദ്രത",
      "weather.rainfall": "മഴയുടെ അളവ്",
      "weather.wind": "കാറ്റിന്റെ വേഗം",
      "weather.condition": "സ്ഥിതി",
      "weather.visibility": "ദൃശ്യത",
      "weather.forecast": "പ്രവചനം",
      "weather.drought_alert": "വറ്റൽ അപകടം: ജലസേചനം പരിഗണിക്കുക",
      "weather.heavy_rain_alert": "കനത്ത മഴ മുന്നറിയിപ്പ്: വിളകൾ സംരക്ഷിക്കുക",
      "weather.irrigation_suggest": "ഉയർന്ന താപനില: ജലസേചനം ആവശ്യമാണ്",
      "weather.growing_season": "നല്ല വളർച്ചാ കാലാവസ്ഥ",
      "weather.disease_risk": "ഉയർന്ന ആർദ്രത: രോഗം സാധ്യത",
      "nav.soil_crop_advice": "മണ്ണും വിളയും ഉപദേശം",
      "nav.pest_disease": "കീടവും രോഗവും തിരിച്ചറിയല്‍",
    },
  },
  kn: {
    translation: {
      "welcome": "ಮುಖಪುಟ",
      "ai_farm_assistant": "ಎಐ ಸಹಾಯಕ",
      "get_instant_answers": "ನಿಮ್ಮ ಕೃಷಿ ಪ್ರಶ್ನೆಗಳಿಗೆ ತ್ವರಿಕ്ಯ ಉತ್ತರಗಳನ್ನು ಪಡೆಯಿರಿ",
      "hero.alt_modern_farming": "ಎಐ ತಕನಿಕೀಯಾನ್ನಿಂಚಿ ನ್ಯೂನ ಕೃಷಿ",
      "hero.title1": "ನಿಮ್ಮ ಎಐ ಆಧಾರಿತ",
      "hero.title2": "ಕೃಷಿ ಸಹಾಯಕ",
      "hero.subtitle": "ವ್ಯಕ್ತಿಗತ ಕೃಷಿ ಸಮಾಧಾನಂ, ಪುಟ್ಟಿನ್ನು ಗುರುತಿಂಪು, ವಾತಾವರಣ ಮಾನಿಕ്ಕುಕೋವಡಂ ಮರಿಯುವುದು ಮತ್ತು ಮಾರ್ಕೆಟ್ ಡೇಟಾ - ನಿಮ್ಮ ಸ್ಥಾನಿಕ ಭಾಷೆಯಲ್ಲಿ, ಎಲ್ಲೆಯಲ್ಲಿ ಅನುಮಾನಗೊಳ್ಳುವುದು.",
      "hero.start_chat": "ಚಾಟ್ ಸಹಾಯಕವನ್ನು ಪ್ರಾರಂಭಿಸಿ",
      "hero.identify_plants": "ಪುಟ್ಟಿನ್ನು ಗುರುತಿಂಪು ಮಾಡಿ",
      "hero.ai_chat_title": "ಎಐ ಚಾಟ್ ಸಹಾಯಕ",
      "hero.ai_chat_desc": "ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿ ವಿಳಕೆಗಳು, ರೋಗಗಳು ಮತ್ತು ಕೃಷಿ ಪ್ರಾಸ್ತ್ರಾಲ್ಲೆಗಳ ಬಗ್ಗೆ ತ್ವರಿಕ്ಯ ಉತ್ತರಗಳನ್ನು ಪಡೆಯಿರಿ",
      "hero.weather_title": "ವಾತಾವರಣ ಮಾನಿಕ്ಕೋವಡಂ",
      "hero.weather_desc": "ನಿಮ್ಮ ಸ್ಥಾನದಲ್ಲಿ ವಾಸ್ತವ ಸಮಯ ವಾತಾವರಣ ಡೇಟಾ ಮತ್ತು ಜಲವಾಯು ಸ್ಮಾರ്ಟ್ ಸಿಫಾರಿಸ್ಲುಗಳು",
      "hero.market_title": "ಮಾರ್ಕೆಟ್ ಅಂತರ್ದೃಷ್ಟಿ",
      "hero.market_desc": "ನಿಮ್ಮ ಲಾಭಾನ್ನಿನಿಂದ ಅಧಿಕಿಸಿಕ്ಕുವುದು ವರ್ತಮಾನ ಮಾರ್ಕೆಟ್ ಧರಗಳು ಮತ್ತು ಪೋಕ್ಕೆಗಳನ್ನು ಅಡಿಗೆಯಿರಿ",
      "nav.home": "ಮುಖಪುಟ",
      "nav.ai_assistant": "ಎಐ ಸಹಾಯಕ",
      "nav.weather": "ಹವಾಮಾನ",
      "nav.market": "ಮಾರುಕಟ್ಟೆ",
      "nav.plant_id": "ಸಸ್ಯ ಗುರುತಿಂಪು",
      "nav.brand": "FarmAI",
      "nav.brand_full": "FarmAI ಸಹಾಯಕ",
      "nav.brand_subtitle": "",
      "chatbot.ready_to_help": "ಸಹಾಯ ಮಾಡಲು ಸದಾ ಸಿದ್ಧವಾಗಿದೆ",
      "chatbot.input_placeholder": "ಬೆಳೆಗಳು, ರೋಗಗಳು, ಹವಾಮಾನ, ಮಾರುಕಟ್ಟೆ ಬೆಲೆಗಳ ಬಗ್ಗೆ ಕೇಳಿ...",
      "chatbot.speech_mode": "ಧ್ವನಿ ಮೋಡ್",
      "chatbot.play_response": "ಪ್ರತ್ಯುತ್ತರ ಓದಿ",
      "weather.loading": "ಹವಾಮಾನ ಡೇಟಾ ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
      "weather.error": "ಹವಾಮಾನ ಡೇಟಾ ಪಡೆಯಲು ವಿಫಲವಾಗಿದೆ.",
      "weather.listen": "ಕೆಳಿ",
      "weather.current_weather_in": "{{city}} ನಲ್ಲಿ ಪ್ರಸ್ತುತ ಹವಾಮಾನ",
      "weather.temp": "ತಾಪಮಾನ",
      "weather.humidity": "ಆದ್ರತೆ",
      "weather.rainfall": "ಮಳೆ ಪ್ರಮಾಣ",
      "weather.wind": "ಗಾಳಿ ವೇಗ",
      "weather.condition": "ಸ್ಥಿತಿ",
      "weather.visibility": "ಗೋಚರತೆ",
      "weather.forecast": "ಅನುವಾದ",
      "weather.drought_alert": "ಬೇಸಿಗೆ ಅಪಾಯ: ನೀರಾವರಿ ಪರಿಗಣಿಸಿ",
      "weather.heavy_rain_alert": "ಭಾರಿ ಮಳೆಯ ಎಚ್ಚರಿಕെ: ಬೆಳೆಗಳನ್ನು ರಕ್ಷಿಸಿ",
      "weather.irrigation_suggest": "ಹೆಚ್ಚು ತಾಪಮಾನ: ನೀರಾವರಿ ಅಗತ್ಯವಿದೆ",
      "weather.growing_season": "ಉತ್ತಮ ಬೆಳೆಯುವ ಕಾಲ",
      "weather.disease_risk": "ಹೆಚ್ಚು ಆದ್ರತೆ: ರೋಗದ ಅಪಾಯ",
      "nav.soil_crop_advice": "ಮಣ್ಣು ಮತ್ತು ಬೆಳೆ ಸಲಹೆ",
      "nav.pest_disease": "ಹುಳು ಮತ್ತು ರೋಗ ಪತ್ತೆ",
    },
  },
  mr: {
    translation: {
      "welcome": "मुख्यपृष्ठ",
      "ai_farm_assistant": "एआय सहाय्यक",
      "get_instant_answers": "विचारा...",
      "hero.alt_modern_farming": "एआय तकनीक के साथ आधुनिक कृषि",
      "hero.title1": "तुमचा एआय आधारित",
      "hero.title2": "कृषी सहाय्यक",
      "hero.subtitle": "व्यक्तिगत कृषी समाधान, पौधों की ओळख, मौसम की जाणकारी आणि बाजार डेटा - तुमच्या स्थानीय भाषेत, कुदाचे अणुवर्तन करण्यास उपलब्ध.",
      "hero.start_chat": "चाट सहायक सुरू करा",
      "hero.identify_plants": "पौधों की ओळख करा",
      "hero.ai_chat_title": "एआय चाट सहायक",
      "hero.ai_chat_desc": "तुमच्या भाषेत फसले, रोग, आणि कृषी अभ्यासांच्या बाबत तुरंत उत्तर प्राप्त करा",
      "hero.weather_title": "मौसम बुद्धिमत्ता",
      "hero.weather_desc": "तुमच्या ठिकाणावर वास्तविक वेळ मौसम डेटा आणि जलवायु-स्मार्ट सिफारिशें",
      "hero.market_title": "बाजार अंतर्दृष्टि",
      "hero.market_desc": "तुमच्या फायद्याचा अधिकतम करण्यास वर्तमान बाजार किमती आणि विचार प्राप्त करा",
      "nav.home": "मुख्यपृष्ठ",
      "nav.ai_assistant": "एआय सहायक",
      "nav.weather": "हवामान",
      "nav.market": "बाजार",
      "nav.plant_id": "वनस्पती ओळख",
      "nav.brand": "FarmAI",
      "nav.brand_full": "FarmAI सहाय्यक",
      "nav.brand_subtitle": "",
      "chatbot.ready_to_help": "सहाय्य करण्यास नेहमी तयार",
      "chatbot.input_placeholder": "पिके, रोग, हवामान, बाजारभाव याबद्दल विचारा...",
      "chatbot.speech_mode": "व्हॉईस मोड",
      "chatbot.play_response": "उत्तर वाचा",
      "weather.loading": "हवामान डेटा लोड होत आहे...",
      "weather.error": "हवामान डेटा मिळवण्यात अयशस्वी.",
      "weather.listen": "ऐका",
      "weather.current_weather_in": "{{city}} मधील वर्तमान हवामान",
      "weather.temp": "तापमान",
      "weather.humidity": "आर्द्रता",
      "weather.rainfall": "पर्जन्यमान",
      "weather.wind": "वाऱ्याचा वेग",
      "weather.condition": "स्थिती",
      "weather.visibility": "दृश्यता",
      "weather.forecast": "अंदाज",
      "weather.drought_alert": "दुष्काळाचा धोका: सिंचनाचा विचार करा",
      "weather.heavy_rain_alert": "जोरदार पावसाचा इशारा: पिकांचे संरक्षण करा",
      "weather.irrigation_suggest": "उच्च तापमान: सिंचन आवश्यक",
      "weather.growing_season": "चांगली वाढीची हंगाम स्थिती",
      "weather.disease_risk": "जास्त आर्द्रता: रोगाचा धोका",
      "nav.soil_crop_advice": "माती आणि पिक सल्ला",
      "nav.pest_disease": "कीटक आणि रोग ओळख",
    },
  },
  gu: {
    translation: {
      "welcome": "મુખ્ય પૃષ્ઠ",
      "ai_farm_assistant": "એઆઈ સહાયક",
      "get_instant_answers": "વિચારો...",
      "hero.alt_modern_farming": "એઆઈ તકનિકીયાન્નિંચિ ન્યુન કૃષિ",
      "hero.title1": "તુમચો એઆઈ આધારિત",
      "hero.title2": "કૃષી સહાયક",
      "hero.subtitle": "વિકલ્પ કૃષી સમાધાન, પુટ્ટિન્નુ ગુરુત્તો, વાતાવરણ માનિક્કોવડં અને માર્કેટ ડેટા - તુમચો સ્થાનિક ભાષામાં, કુદાચે અનુમાન કરવામાં ઉપલબ્ધ.",
      "hero.start_chat": "ચાટ સહાયક શરૂ કરો",
      "hero.identify_plants": "પુટ્ટિન્નુ ગુરુત્તો કરો",
      "hero.ai_chat_title": "એઆઈ ચાટ સહાયક",
      "hero.ai_chat_desc": "તુમચો ભાષામાં વિળકો, રોગ, અને કૃષી અભ્યાસાંચી બાબતી તુરંગી ઉત્તર પ્રાપ્ત કરો",
      "hero.weather_title": "વાતાવરણ માનિક્કોવડં",
      "hero.weather_desc": "તુમચો સ્થાનદારે વાસ્તવિક વખતે વાતાવરણ ડેટા અને જલવાયુ-સ્માર્ટ સિફારિસ્લુંકીયાં",
      "hero.market_title": "માર્કેટ અંતર્દૃષ્ટિ",
      "hero.market_desc": "તુમચો ફાયદોની અધિકિત કરવામાં વર્તમાન માર્કેટ કિમતી અને પોક્કીઓ અડિગો.",
      "nav.home": "મુખ્ય પૃષ્ઠ",
      "nav.ai_assistant": "એઆઈ સહાયક",
      "nav.weather": "હવામાન",
      "nav.market": "માર્કેટ",
      "nav.plant_id": "વનસ્પતિ ઓળખ",
      "nav.brand": "FarmAI",
      "nav.brand_full": "એઆઈ સહાયક",
      "nav.brand_subtitle": "",
      "chatbot.ready_to_help": "સહાય માટે હંમેશા તૈયાર",
      "chatbot.input_placeholder": "પાક, રોગ, હવામાન, બજાર ભાવ વિશે પૂછો...",
      "chatbot.speech_mode": "વોઇસ મોડ",
      "chatbot.play_response": "જવાબ વાંચો",
      "weather.loading": "હવામાન ડેટા લોડ થઈ રહ્યું છે...",
      "weather.error": "હવામાન ડેટા મેળવવામાં નિષ્ફળ.",
      "weather.listen": "સાંભળો",
      "weather.current_weather_in": "{{city}} માં વર્તમાન હવામાન",
      "weather.temp": "તાપમાન",
      "weather.humidity": "ભેજ",
      "weather.rainfall": "વરસાદ",
      "weather.wind": "પવનની ઝડપ",
      "weather.condition": "પરિસ્થિતિ",
      "weather.visibility": "દૃશ્યતા",
      "weather.forecast": "અનુમાન",
      "weather.drought_alert": "દુષ્કાળ જોખમ: સિંચાઈ પર વિચાર કરો",
      "weather.heavy_rain_alert": "ભારે વરસાદની ચેતવણી: પાકને સુરક્ષિત કરો",
      "weather.irrigation_suggest": "ઉચ્ચ તાપમાન: સિંચાઈ જરૂરી",
      "weather.growing_season": "સારી વૃદ્ધિ માટેની ઋતુ",
      "weather.disease_risk": "વધુ ભેજ: રોગનો જોખમ",
      "nav.soil_crop_advice": "માટી અને પાક સલાહ",
      "nav.pest_disease": "કીડા અને રોગ ઓળખ",
    },
  },
  pa: {
    translation: {
      "welcome": "ਮੁੱਖ ਪੰਨਾ",
      "ai_farm_assistant": "ਏਆਈ ਸਹਾਇਕ",
      "get_instant_answers": "ਵਿਚਾਰੋ...",
      "hero.alt_modern_farming": "ਏਆਈ ਤਕਨਿਕੀਯਾਨਿੰਚੀ ਨ੍ਯੂਨ ਕ੃਷ਿ",
      "hero.title1": "ਤੁਹਾਡਾ ਏਆਈ ਆਧਾਰਿਤ",
      "hero.title2": "ਕ੃਷ੀ ਸਹਾਇਕ",
      "hero.subtitle": "ਵਿਕਲਪੀ ਕ੃਷ੀ ਸਮਾਧਾਨ, ਪੁੱਟ੍ਟੀਨ੍ਨੁ ਗੁਰੂਤਵੋ, ਵਾਤਾਵਰਣ ਮਾਨਿਕ੍ਕੋਵਡਂ ਅਤੇ ਮਾਰਕੇਟ ਡੇਟਾ - ਤੁਹਾਡੇ ਸਥਾਨੀਕ ਭਾ਷ਾ ਵਿੱਚ, ਕੁਦਾਚੇ ਅਨੁਮਾਨ ਕਰਵਾ ਲਈ ਉਪਲਬ੍ਧ.",
      "hero.start_chat": "ਚਾਟ ਸਹਾਇਕ ਸ਼ਰੂ ਕਰੋ",
      "hero.identify_plants": "ਪੁੱਟ੍ਟੀਨ੍ਨੁ ਗੁਰੂਤਵੋ ਕਰੋ",
      "hero.ai_chat_title": "ਏਆਈ ਚਾਟ ਸਹਾਇਕ",
      "hero.ai_chat_desc": "ਤੁਹਾਡੇ ਭਾ਷ਾ ਵਿੱਚ ਵਿਲ਼ਕੋਂ, ਰੋਗ, ਅਤੇ ਕ੃਷ੀ ਅਭਿਆਸਾਂ ਦੀ ਬਾਬਤੀ ਤੁਰਾਂਗੀ ਉਤਤਰ ਪ੍ਰਾਪਤ ਕਰੋ",
      "hero.weather_title": "ਵਾਤਾਵਰਣ ਮਾਨਿਕ੍ਕੋਵਡਂ",
      "hero.weather_desc": "ਤੁਹਾਡੇ ਸਥਾਨ ਦਾਰੀ ਵਖਤੇ ਵਾਤਾਵਰਣ ਡੇਟਾ ਅਤੇ ਜਲਵਾੁ-ਸਮਾਰਟ ਸਿਫਾਰਿਸ਼ੀਕਾਂ",
      "hero.market_title": "ਮਾਰਕੇਟ ਅੰਤਰਦ੃਷ਤੀ",
      "hero.market_desc": "ਤੁਹਾਡੇ ਫਾਈਦੇ ਨੂੰ ਅੱਖਰਾਂ ਕਰਵਾ ਲਈ ਵਰਤਮਾਨ ਮਾਰਕੇਟ ਕੀਮਤੀ ਅਤੇ ਪੋਕੀਓਂ ਪ੍ਰਾਪਤ ਕਰੋ",
      "nav.home": "ਮੁੱਖ ਪੰਨਾ",
      "nav.ai_assistant": "ਏਆਈ ਸਹਾਇਕ",
      "nav.weather": "ਮੌਸਮ",
      "nav.market": "ਬਾਜ਼ਾਰ",
      "nav.plant_id": "ਪੌਦੇ ਦੀ ਪਛਾਣ",
      "nav.brand": "FarmAI",
      "nav.brand_full": "ਏਆਈ ਸਹਾਇਕ",
      "nav.brand_subtitle": "",
      "chatbot.ready_to_help": "ਹਮੇਸ਼ਾ ਮਦਦ ਲਈ ਤਿਆਰ",
      "chatbot.input_placeholder": "ਫਸਲਾਂ, ਬਿਮਾਰੀਆਂ, ਮੌਸਮ, ਬਾਜ਼ਾਰ ਦੀਆਂ ਕੀਮਤਾਂ ਬਾਰੇ ਪੁੱਛੋ...",
      "chatbot.speech_mode": "ਵੌਇਸ ਮੋਡ",
      "chatbot.play_response": "ਜਵਾਬ ਪੜ੍ਹੋ",
      "weather.loading": "ਮੌਸਮ ਡਾਟਾ ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...",
      "weather.error": "ਮੌਸਮ ਡਾਟਾ ਪ੍ਰਾਪਤ ਕਰਨ ਵਿੱਚ ਅਸਫਲ.",
      "weather.listen": "ਸੁਣੋ",
      "weather.current_weather_in": "{{city}} ਵਿੱਚ ਮੌਜੂਦਾ ਮੌਸਮ",
      "weather.temp": "ਤਾਪਮਾਨ",
      "weather.humidity": "ਨਮੀ",
      "weather.rainfall": "ਵਰਖਾ",
      "weather.wind": "ਹਵਾ ਦੀ ਰਫਤਾਰ",
      "weather.condition": "ਹਾਲਤ",
      "weather.visibility": "ਦਿੱਖ",
      "weather.forecast": "ਭਵਿੱਖਬਾਣੀ",
      "weather.drought_alert": "ਸੂਕਾ ਖਤਰਾ: ਸਿੰਚਾਈ ਬਾਰੇ ਸੋਚੋ",
      "weather.heavy_rain_alert": "ਭਾਰੀ ਵਰਖਾ ਚੇਤਾਵਨੀ: ਫਸਲਾਂ ਦੀ ਰੱਖਿਆ ਕਰੋ",
      "weather.irrigation_suggest": "ਵੱਧ ਤਾਪਮਾਨ: ਸਿੰਚਾਈ ਲਾਜ਼ਮੀ",
      "weather.growing_season": "ਚੰਗਾ ਵਧਣ ਦਾ ਮੌਸਮ",
      "weather.disease_risk": "ਵੱਧ ਨਮੀ: ਬਿਮਾਰੀ ਦਾ ਖਤਰਾ",
      "nav.soil_crop_advice": "ਮਿੱਟੀ ਅਤੇ ਫਸਲ ਸਲਾਹ",
      "nav.pest_disease": "ਕੀੜੇ ਅਤੇ ਬਿਮਾਰੀ ਪਛਾਣ",
    },
  },
  bn: { translation: { "welcome": "Welcome to Farmer AI Buddy!", /* ...copy keys from 'en' as needed... */ } },
  ur: { translation: { "welcome": "Welcome to Farmer AI Buddy!", /* ...copy keys from 'en' as needed... */ } },
  as: { translation: { "welcome": "Welcome to Farmer AI Buddy!", /* ...copy keys from 'en' as needed... */ } },
  or: { translation: { "welcome": "Welcome to Farmer AI Buddy!", /* ...copy keys from 'en' as needed... */ } },
};

i18n
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    resources,
    fallbackLng: "en",
    interpolation: {
      escapeValue: false,
    },
    detection: {
      order: ["localStorage", "navigator"],
      caches: ["localStorage"],
    },
  });

export default i18n;

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}

// Utility functions for farming assistant

// City to district mapping (expand as needed)
const cityToDistrict: Record<string, string> = {
  Chennai: "Kanchipuram",
  Coimbatore: "Coimbatore",
  Madurai: "Madurai",
  Salem: "Salem",
  Tiruchirappalli: "Tiruchirappalli",
  Tirunelveli: "Tirunelveli",
  Vellore: "Vellore",
  Erode: "Erode",
  Kanchipuram: "Kanchipuram",
  Thanjavur: "Thanjavur"
};

export function mapCityToDistrict(city: string): string {
  return cityToDistrict[city] || city;
}

// Weather API (OpenWeatherMap) - replace with real API key and endpoint
export interface WeatherData {
  temp: number;
  humidity: number;
  rainfall: number;
}

export async function fetchWeatherData(district: string): Promise<WeatherData> {
  // In production, use fetch with OpenWeatherMap API
  // For now, return mock data
  return {
    temp: 32,
    humidity: 70,
    rainfall: 5
  };
}

// Season logic (simplified)
const districtSeasons: Record<string, { start: number; end: number; name: string }[]> = {
  Kanchipuram: [
    { start: 6, end: 9, name: "Kuruvai" },
    { start: 10, end: 12, name: "Thaladi" },
    { start: 1, end: 5, name: "Samba" }
  ],
  // ...add for other districts
};

export function getCurrentSeason(date: Date, district: string): string {
  const month = date.getMonth() + 1;
  const seasons = districtSeasons[district] || districtSeasons["Kanchipuram"];
  const found = seasons.find(s => month >= s.start && month <= s.end);
  return found ? found.name : "General";
}

// Crop advice (mock)
export interface CropAdvice {
  crops: { name: string; details: string }[];
  tips: string;
}

export function getCropAdvice(season: string, district: string, lang: string): CropAdvice {
  // In production, fetch from API or DB, and translate
  if (season === "Kuruvai") {
    return {
      crops: [
        { name: "Paddy", details: "Sow short-duration varieties. Irrigate regularly." },
        { name: "Blackgram", details: "Suitable for Kuruvai in delta regions." }
      ],
      tips: lang === "ta" ? "நீர்ப்பாசனம் அவசியம். பூச்சி மேலாண்மை கவனிக்கவும்." : "Ensure irrigation. Monitor for pests."
    };
  }
  return {
    crops: [
      { name: "Paddy", details: "General advice for paddy." }
    ],
    tips: lang === "ta" ? "பயிர் பராமரிப்பு அவசியம்." : "Crop care is essential."
  };
}
